[2024-02-26T14:55:16.936+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509
[2024-02-26T14:55:16.937+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti'
[2024-02-26T14:55:16.966+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509
[2024-02-26T14:55:16.966+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti'
[2024-02-26T14:55:17.001+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_dag_with_slack_webhook.raise_exception_and_send_slack_noti scheduled__2024-01-01T00:30:00+00:00 [queued]>
[2024-02-26T14:55:17.009+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_dag_with_slack_webhook.raise_exception_and_send_slack_noti scheduled__2024-01-01T00:30:00+00:00 [queued]>
[2024-02-26T14:55:17.010+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-26T14:55:17.032+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): raise_exception_and_send_slack_noti> on 2024-01-01 00:30:00+00:00
[2024-02-26T14:55:17.038+0000] {standard_task_runner.py:57} INFO - Started process 1729 to run task
[2024-02-26T14:55:17.041+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'python_dag_with_slack_webhook', 'raise_exception_and_send_slack_noti', 'scheduled__2024-01-01T00:30:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/05-python-operator-with-slack-noti.py', '--cfg-path', '/tmp/tmp0fbe6qm3']
[2024-02-26T14:55:17.045+0000] {standard_task_runner.py:85} INFO - Job 107: Subtask raise_exception_and_send_slack_noti
[2024-02-26T14:55:17.113+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509
[2024-02-26T14:55:17.114+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti'
[2024-02-26T14:55:17.116+0000] {task_command.py:410} INFO - Running <TaskInstance: python_dag_with_slack_webhook.raise_exception_and_send_slack_noti scheduled__2024-01-01T00:30:00+00:00 [running]> on host 2fe49a870f57
[2024-02-26T14:55:17.225+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='heumsi' AIRFLOW_CTX_DAG_ID='python_dag_with_slack_webhook' AIRFLOW_CTX_TASK_ID='raise_exception_and_send_slack_noti' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:30:00+00:00'
[2024-02-26T14:55:17.227+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/05-python-operator-with-slack-noti.py", line 17, in _handle_job_error
    raise AirflowFailException("Job failed")
airflow.exceptions.AirflowFailException: Job failed
[2024-02-26T14:55:17.240+0000] {taskinstance.py:1350} INFO - Immediate failure requested. Marking task as FAILED. dag_id=python_dag_with_slack_webhook, task_id=raise_exception_and_send_slack_noti, execution_date=20240101T003000, start_date=20240226T145517, end_date=20240226T145517
[2024-02-26T14:55:17.254+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 107 for task raise_exception_and_send_slack_noti (Job failed; 1729)
[2024-02-26T14:55:17.294+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-02-26T14:55:17.311+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-26T15:06:41.725+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509
[2024-02-26T15:06:41.726+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti'
[2024-02-26T15:06:41.753+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509
[2024-02-26T15:06:41.754+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti'
[2024-02-26T15:06:41.785+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_dag_with_slack_webhook.raise_exception_and_send_slack_noti scheduled__2024-01-01T00:30:00+00:00 [queued]>
[2024-02-26T15:06:41.794+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_dag_with_slack_webhook.raise_exception_and_send_slack_noti scheduled__2024-01-01T00:30:00+00:00 [queued]>
[2024-02-26T15:06:41.795+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-26T15:06:41.819+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): raise_exception_and_send_slack_noti> on 2024-01-01 00:30:00+00:00
[2024-02-26T15:06:41.832+0000] {standard_task_runner.py:57} INFO - Started process 1936 to run task
[2024-02-26T15:06:41.834+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'python_dag_with_slack_webhook', 'raise_exception_and_send_slack_noti', 'scheduled__2024-01-01T00:30:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/05-python-operator-with-slack-noti.py', '--cfg-path', '/tmp/tmpv2flj96h']
[2024-02-26T15:06:41.836+0000] {standard_task_runner.py:85} INFO - Job 110: Subtask raise_exception_and_send_slack_noti
[2024-02-26T15:06:41.893+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509
[2024-02-26T15:06:41.894+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-01T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti'
[2024-02-26T15:06:41.896+0000] {task_command.py:410} INFO - Running <TaskInstance: python_dag_with_slack_webhook.raise_exception_and_send_slack_noti scheduled__2024-01-01T00:30:00+00:00 [running]> on host 2fe49a870f57
[2024-02-26T15:06:41.988+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='heumsi' AIRFLOW_CTX_DAG_ID='python_dag_with_slack_webhook' AIRFLOW_CTX_TASK_ID='raise_exception_and_send_slack_noti' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:30:00+00:00'
[2024-02-26T15:06:41.992+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/05-python-operator-with-slack-noti.py", line 17, in _handle_job_error
    raise AirflowFailException("Job failed")
airflow.exceptions.AirflowFailException: Job failed
[2024-02-26T15:06:42.008+0000] {taskinstance.py:1350} INFO - Immediate failure requested. Marking task as FAILED. dag_id=python_dag_with_slack_webhook, task_id=raise_exception_and_send_slack_noti, execution_date=20240101T003000, start_date=20240226T150641, end_date=20240226T150642
[2024-02-26T15:06:42.023+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 110 for task raise_exception_and_send_slack_noti (Job failed; 1936)
[2024-02-26T15:06:42.054+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-02-26T15:06:42.085+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
