[2024-02-26T13:41:48.032+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=Hello_world/run_id=scheduled__2024-02-24T06:00:00+00:00/task_id=print_hello permission to 509
[2024-02-26T13:41:48.033+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=Hello_world/run_id=scheduled__2024-02-24T06:00:00+00:00/task_id=print_hello permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Hello_world/run_id=scheduled__2024-02-24T06:00:00+00:00/task_id=print_hello'
[2024-02-26T13:41:48.289+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=Hello_world/run_id=scheduled__2024-02-24T06:00:00+00:00/task_id=print_hello permission to 509
[2024-02-26T13:41:48.290+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=Hello_world/run_id=scheduled__2024-02-24T06:00:00+00:00/task_id=print_hello permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Hello_world/run_id=scheduled__2024-02-24T06:00:00+00:00/task_id=print_hello'
[2024-02-26T13:41:48.330+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Hello_world.print_hello scheduled__2024-02-24T06:00:00+00:00 [queued]>
[2024-02-26T13:41:48.338+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Hello_world.print_hello scheduled__2024-02-24T06:00:00+00:00 [queued]>
[2024-02-26T13:41:48.339+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-26T13:41:48.359+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): print_hello> on 2024-02-24 06:00:00+00:00
[2024-02-26T13:41:48.367+0000] {standard_task_runner.py:57} INFO - Started process 74 to run task
[2024-02-26T13:41:48.371+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Hello_world', 'print_hello', 'scheduled__2024-02-24T06:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/hello_world.py', '--cfg-path', '/tmp/tmpczgu0rsc']
[2024-02-26T13:41:48.374+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask print_hello
[2024-02-26T13:41:48.442+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=Hello_world/run_id=scheduled__2024-02-24T06:00:00+00:00/task_id=print_hello permission to 509
[2024-02-26T13:41:48.442+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=Hello_world/run_id=scheduled__2024-02-24T06:00:00+00:00/task_id=print_hello permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Hello_world/run_id=scheduled__2024-02-24T06:00:00+00:00/task_id=print_hello'
[2024-02-26T13:41:48.444+0000] {task_command.py:410} INFO - Running <TaskInstance: Hello_world.print_hello scheduled__2024-02-24T06:00:00+00:00 [running]> on host 2fe49a870f57
[2024-02-26T13:41:48.540+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='heumsi' AIRFLOW_CTX_DAG_ID='Hello_world' AIRFLOW_CTX_TASK_ID='print_hello' AIRFLOW_CTX_EXECUTION_DATE='2024-02-24T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-24T06:00:00+00:00'
[2024-02-26T13:41:48.542+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-26T13:41:48.543+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'hello"]
[2024-02-26T13:41:48.560+0000] {subprocess.py:86} INFO - Output:
[2024-02-26T13:41:48.562+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2024-02-26T13:41:48.562+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2024-02-26T13:41:48.563+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-02-26T13:41:48.573+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-02-26T13:41:48.576+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=Hello_world, task_id=print_hello, execution_date=20240224T060000, start_date=20240226T134148, end_date=20240226T134148
[2024-02-26T13:41:48.590+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 5 for task print_hello (Bash command failed. The command returned a non-zero exit code 2.; 74)
[2024-02-26T13:41:48.625+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-02-26T13:41:48.650+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
