[2024-02-26T14:55:17.150+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509
[2024-02-26T14:55:17.152+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti'
[2024-02-26T14:55:17.193+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509
[2024-02-26T14:55:17.193+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti'
[2024-02-26T14:55:17.224+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_dag_with_slack_webhook.raise_exception_and_send_slack_noti scheduled__2024-01-03T00:30:00+00:00 [queued]>
[2024-02-26T14:55:17.238+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_dag_with_slack_webhook.raise_exception_and_send_slack_noti scheduled__2024-01-03T00:30:00+00:00 [queued]>
[2024-02-26T14:55:17.239+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-26T14:55:17.255+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): raise_exception_and_send_slack_noti> on 2024-01-03 00:30:00+00:00
[2024-02-26T14:55:17.262+0000] {standard_task_runner.py:57} INFO - Started process 1731 to run task
[2024-02-26T14:55:17.265+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'python_dag_with_slack_webhook', 'raise_exception_and_send_slack_noti', 'scheduled__2024-01-03T00:30:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/05-python-operator-with-slack-noti.py', '--cfg-path', '/tmp/tmp9uwu5_zi']
[2024-02-26T14:55:17.267+0000] {standard_task_runner.py:85} INFO - Job 109: Subtask raise_exception_and_send_slack_noti
[2024-02-26T14:55:17.309+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509
[2024-02-26T14:55:17.309+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti'
[2024-02-26T14:55:17.312+0000] {task_command.py:410} INFO - Running <TaskInstance: python_dag_with_slack_webhook.raise_exception_and_send_slack_noti scheduled__2024-01-03T00:30:00+00:00 [running]> on host 2fe49a870f57
[2024-02-26T14:55:17.393+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='heumsi' AIRFLOW_CTX_DAG_ID='python_dag_with_slack_webhook' AIRFLOW_CTX_TASK_ID='raise_exception_and_send_slack_noti' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:30:00+00:00'
[2024-02-26T14:55:17.395+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/05-python-operator-with-slack-noti.py", line 17, in _handle_job_error
    raise AirflowFailException("Job failed")
airflow.exceptions.AirflowFailException: Job failed
[2024-02-26T14:55:17.408+0000] {taskinstance.py:1350} INFO - Immediate failure requested. Marking task as FAILED. dag_id=python_dag_with_slack_webhook, task_id=raise_exception_and_send_slack_noti, execution_date=20240103T003000, start_date=20240226T145517, end_date=20240226T145517
[2024-02-26T14:55:17.419+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 109 for task raise_exception_and_send_slack_noti (Job failed; 1731)
[2024-02-26T14:55:17.437+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-02-26T14:55:17.453+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-26T15:06:42.174+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509
[2024-02-26T15:06:42.176+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti'
[2024-02-26T15:06:42.216+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509
[2024-02-26T15:06:42.217+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti'
[2024-02-26T15:06:42.247+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_dag_with_slack_webhook.raise_exception_and_send_slack_noti scheduled__2024-01-03T00:30:00+00:00 [queued]>
[2024-02-26T15:06:42.258+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_dag_with_slack_webhook.raise_exception_and_send_slack_noti scheduled__2024-01-03T00:30:00+00:00 [queued]>
[2024-02-26T15:06:42.258+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-26T15:06:42.278+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): raise_exception_and_send_slack_noti> on 2024-01-03 00:30:00+00:00
[2024-02-26T15:06:42.283+0000] {standard_task_runner.py:57} INFO - Started process 1938 to run task
[2024-02-26T15:06:42.286+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'python_dag_with_slack_webhook', 'raise_exception_and_send_slack_noti', 'scheduled__2024-01-03T00:30:00+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/05-python-operator-with-slack-noti.py', '--cfg-path', '/tmp/tmpmlgyurq9']
[2024-02-26T15:06:42.288+0000] {standard_task_runner.py:85} INFO - Job 112: Subtask raise_exception_and_send_slack_noti
[2024-02-26T15:06:42.336+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509
[2024-02-26T15:06:42.337+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_slack_webhook/run_id=scheduled__2024-01-03T00:30:00+00:00/task_id=raise_exception_and_send_slack_noti'
[2024-02-26T15:06:42.339+0000] {task_command.py:410} INFO - Running <TaskInstance: python_dag_with_slack_webhook.raise_exception_and_send_slack_noti scheduled__2024-01-03T00:30:00+00:00 [running]> on host 2fe49a870f57
[2024-02-26T15:06:42.425+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='heumsi' AIRFLOW_CTX_DAG_ID='python_dag_with_slack_webhook' AIRFLOW_CTX_TASK_ID='raise_exception_and_send_slack_noti' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:30:00+00:00'
[2024-02-26T15:06:42.427+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/05-python-operator-with-slack-noti.py", line 17, in _handle_job_error
    raise AirflowFailException("Job failed")
airflow.exceptions.AirflowFailException: Job failed
[2024-02-26T15:06:42.437+0000] {taskinstance.py:1350} INFO - Immediate failure requested. Marking task as FAILED. dag_id=python_dag_with_slack_webhook, task_id=raise_exception_and_send_slack_noti, execution_date=20240103T003000, start_date=20240226T150642, end_date=20240226T150642
[2024-02-26T15:06:42.450+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 112 for task raise_exception_and_send_slack_noti (Job failed; 1938)
[2024-02-26T15:06:42.498+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-02-26T15:06:42.513+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
